// packages/react/src/component/wrapper.tsx
import type { CoreResolvedWrapperConfig } from '@piying/view-core';
import { useMemo } from 'react';
import { useSignalToRef } from '../util/signal-convert';

export interface PiyingWrapperProps {
  wrappers: CoreResolvedWrapperConfig[];
  children: any;
}

export function PiyingWrapper(props: PiyingWrapperProps) {
  const restWrappers = useMemo(
    () => props.wrappers!.slice(1),
    [props.wrappers],
  );
  const wrapper = props.wrappers[0];
  const inputs = useSignalToRef(wrapper, () => ({
    ...wrapper?.inputs(),
    ...wrapper?.attributes(),
    ...wrapper?.outputs,
  }));
  return (
    <>
      {wrapper ? (
        <wrapper.type {...inputs}>
          <PiyingWrapper wrappers={restWrappers}>
            {props.children}
          </PiyingWrapper>
        </wrapper.type>
      ) : (
        props.children
      )}
    </>
  );
}

// packages/solid/src/component/wrapper.tsx
import type { CoreResolvedWrapperConfig } from '@piying/view-core';
import { useSignalToRef } from '../util/signal-convert';
import { createMemo, Show } from 'solid-js';

export interface PiyingWrapperProps {
  wrappers: CoreResolvedWrapperConfig[];
  children: any;
}

export function PiyingWrapper(props: PiyingWrapperProps) {
  const wrapper = createMemo(() => props.wrappers[0]);
  const restWrappers = createMemo(() => props.wrappers?.slice(1));
  const inputs = useSignalToRef(() => ({
    ...wrapper()?.inputs(),
    ...wrapper()?.attributes(),
    ...wrapper()?.outputs,
  }));
  return (
    <Show
      when={createMemo(() => wrapper()?.type)()}
      fallback={props.children}
      keyed
    >
      {(WrapperType) => {
        return (
          <WrapperType {...inputs()}>
            <PiyingWrapper wrappers={restWrappers()}>
              {props.children}
            </PiyingWrapper>
          </WrapperType>
        );
      }}
    </Show>
  );
}
