// packages/solid/src/util/signal-convert.ts
import { effect } from 'static-injector';

import { InjectorToken } from '../token';
import { useContext, createEffect, createSignal, onCleanup } from 'solid-js';

// signal=>ref
// todo 重命名
export function useSignalToRef<T>(value: () => T) {
  const injector = useContext(InjectorToken)!;
  const [result, setResult] = createSignal(value());
  createEffect(() => {
    setResult(() => value());
    const ref = effect(
      () => {
        const currentValue = value();
        if (!Object.is(result(), currentValue)) {
          setResult(() => currentValue!);
        }
      },
      { injector: injector },
    );
    onCleanup(() => {
      ref.destroy();
    });
  });
  return result;
}

// packages/react/src/util/signal-convert.ts
import { effect } from 'static-injector';

import { InjectorToken } from '../token';
import { useContext, useEffect, useMemo, useRef, useState } from 'react';

// signal=>ref
export function useSignalToRef<I, R>(listen: I, value: (fn: I) => R) {
  const injector = useContext(InjectorToken)!;
  const [result, setResult] = useState(useMemo(() => value(listen), []));
  const resultRef = useRef(result);
  useEffect(() => {
    const currentValue = value(listen);
    if (!Object.is(resultRef.current, currentValue)) {
      setResult(currentValue);
      resultRef.current = currentValue;
    }
    const ref = effect(
      () => {
        const currentValue = value(listen);
        if (!Object.is(resultRef.current, currentValue)) {
          setResult(currentValue!);
          resultRef.current = currentValue;
        }
      },
      { injector: injector },
    );
    return () => {
      ref.destroy();
    };
  }, [listen, useMemo(() => value, [])]);
  return result;
}
