// packages/solid/src/util/use-control-value-accessor.ts
import type { ControlValueAccessor } from '@piying/view-core';
import { createSignal, type Accessor } from 'solid-js';

export function useControlValueAccessor(optionalBind?: boolean) {
  const [value, setValue] = createSignal<any>(undefined);
  const [disabled, setDisabled] = createSignal(false);
  const [onChange, setOnChange] = createSignal<
    ((input: any) => void) | undefined
  >(undefined);
  const [touched, setTouched] = createSignal<(() => void) | undefined>(
    undefined,
  );
  const cva: ControlValueAccessor = {
    writeValue(obj) {
      setValue(obj);
    },
    registerOnChange(fn) {
      setOnChange(() => fn);
    },
    registerOnTouched(fn) {
      setTouched(() => fn);
    },
    setDisabledState(value) {
      setDisabled(value);
    },
  };

  return {
    cva: cva,
    cvaa: {
      value: value,
      disabled: disabled,
      valueChange: (value: any) => {
        if (optionalBind) {
          onChange()?.(value);
        } else {
          onChange()!(value);
        }
        setValue(value);
      },
      touchedChange: () => {
        if (optionalBind) {
          touched()?.();
        } else {
          touched()!();
        }
      },
    } as ControlValueAccessorAdapter,
  };
}

export type ControlValueAccessorAdapter = {
  value: Accessor<any>;
  disabled: Accessor<boolean>;
  touchedChange: () => void;
  valueChange: (value: any) => void;
};

// packages/react/src/util/use-control-value-accessor.ts
import type { ControlValueAccessor } from '@piying/view-core';
import { useMemo, useRef, useState } from 'react';

export function useControlValueAccessor(optionalBind?: boolean) {
  const [value, setValue] = useState(undefined);
  const [disabled, setDisabled] = useState(false);
  const onChange = useRef<((input: any) => void) | undefined>(undefined);
  const touched = useRef<(() => void) | undefined>(undefined);
  const cva: ControlValueAccessor = useMemo(() => {
    return {
      writeValue(obj) {
        setValue(obj);
      },
      registerOnChange(fn) {
        onChange.current = fn;
      },
      registerOnTouched(fn) {
        touched.current = fn;
      },
      setDisabledState(value) {
        setDisabled(value);
      },
    };
  }, []);
  const cvaa = useMemo(() => {
    return {
      value: value,
      disabled: disabled,
      valueChange: (value: any) => {
        if (optionalBind) {
          onChange.current?.(value);
        } else {
          onChange.current!(value);
        }
        setValue(value);
      },
      touchedChange: () => {
        if (optionalBind) {
          touched.current?.();
        } else {
          touched.current!();
        }
      },
    } as ControlValueAccessorAdapter;
  }, [value, disabled]);
  return useMemo(() => {
    return {
      cva,
      cvaa,
    };
  }, [cvaa]);
}

export type ControlValueAccessorAdapter = {
  value: any;
  disabled: boolean;
  touchedChange: () => void;
  valueChange: (value: any) => void;
};
