// packages/vue/src/component/piying-view.vue
<script setup lang="ts">
import * as v from 'valibot';
import { convert } from '@piying/view-core';
import { computed, inject, onUnmounted, provide, watch } from 'vue';
import {
  ChangeDetectionScheduler,
  ChangeDetectionSchedulerImpl,
  createInjector,
  createRootInjector,
  untracked,
  type EffectRef,
} from 'static-injector';
import { VueSchemaHandle } from '../vue-schema';
import { VueFormBuilder } from '../builder';
import {
  InjectorToken,
  PI_INPUT_MODEL_TOKEN,
  PI_INPUT_OPTIONS_TOKEN,
  PI_INPUT_SCHEMA_TOKEN,
  PI_VIEW_FIELD_TOKEN,
} from '../token';
import FieldTemplate from './field-template.vue';
import type { Injector } from 'static-injector';
import { initListen } from '@piying/view-core';
const inputs = defineProps<{
  schema: v.BaseSchema<any, any, any> | v.SchemaWithPipe<any>;
  modelValue?: any;
  options: { injector?: Injector; [name: string]: any };
}>();

const emit = defineEmits(['update:modelValue']);
const maybeParentField = inject(PI_VIEW_FIELD_TOKEN, undefined);
const rootInjector = computed(() => {
  return (
    inputs.options.injector ??
    maybeParentField?.value.injector ??
    createRootInjector({
      providers: [
        {
          provide: ChangeDetectionScheduler,
          useClass: ChangeDetectionSchedulerImpl,
        },
      ],
    })
  );
});
provide(InjectorToken, rootInjector);
provide(
  PI_INPUT_OPTIONS_TOKEN,
  computed(() => inputs.options as any),
);
provide(
  PI_INPUT_SCHEMA_TOKEN,
  computed(() => inputs.schema),
);
provide(
  PI_INPUT_MODEL_TOKEN,
  computed(() => inputs.modelValue),
);

let injectorDispose: (() => any) | undefined;
const initResult = computed(() => {
  injectorDispose?.();
  const subInjector = createInjector({ providers: [], parent: rootInjector.value });
  injectorDispose = () => {
    subInjector.destroy();
    injectorDispose = undefined;
  };
  const field = convert(inputs.schema as any, {
    ...inputs.options,
    handle: VueSchemaHandle as any,
    builder: VueFormBuilder,
    injector: subInjector,
  });
  return [field, subInjector] as const;
});
onUnmounted(() => {
  injectorDispose?.();
});
const field = computed(() => initResult.value[0]);

watch(
  () => [initResult.value, inputs.modelValue],
  ([[field, subInjector], modelValue], _1, onWatcherCleanup) => {
    let ref: EffectRef | undefined;
    if (field.form.control) {
      ref = initListen(modelValue, field!.form.control!, subInjector as Injector, (value) => {
        untracked(() => {
          if (field!.form.control?.valueNoError$$()) {
            emit('update:modelValue', value);
          }
        });
      });
      field!.form.control!.updateValue(inputs.modelValue);
    }
    onWatcherCleanup(() => {
      ref?.destroy();
    });
  },
  { immediate: true },
);
</script>

<template>
  <field-template :field="field!"></field-template>
</template>

<style scoped></style>

// packages/svelte/src/lib/component/piying-view.svelte
<script lang="ts">
	import * as v from 'valibot';
	import { convert } from '@piying/view-core';
	import {
		ChangeDetectionScheduler,
		ChangeDetectionSchedulerImpl,
		createInjector,
		createRootInjector,
		untracked,
		type EffectRef
	} from 'static-injector';
	import type { Injector } from 'static-injector';
	import { getContext, setContext } from 'svelte';
	import {
		InjectorToken,
		PI_INPUT_MODEL_TOKEN,
		PI_INPUT_OPTIONS_TOKEN,
		PI_INPUT_SCHEMA_TOKEN,
		PI_VIEW_FIELD_TOKEN
	} from '../token';
	import { SvelteSchemaHandle } from '../svelte-schema';
	import { SvelteFormBuilder } from '../builder';
	import FieldTemplate from './field-template.svelte';
	import { initListen } from '@piying/view-core';
	let inputs: {
		schema: v.BaseSchema<any, any, any> | v.SchemaWithPipe<any>;
		model?: any;
		modelChange?: (value: any) => void;
		options: { injector?: Injector; builder?: any; [name: string]: any };
	} = $props();
	const maybeParentField = getContext<PI_VIEW_FIELD_TOKEN>(PI_VIEW_FIELD_TOKEN);
	const rootInjector = $derived.by(() => {
		return (
			inputs.options.injector ??
			maybeParentField?.().injector ??
			createRootInjector({
				providers: [
					{
						provide: ChangeDetectionScheduler,
						useClass: ChangeDetectionSchedulerImpl
					}
				]
			})
		);
	});

	setContext(InjectorToken, () => rootInjector);
	setContext(PI_INPUT_OPTIONS_TOKEN, () => inputs.options);
	setContext(PI_INPUT_SCHEMA_TOKEN, () => inputs.schema);
	setContext(PI_INPUT_MODEL_TOKEN, () => inputs.model);
	let injectorDispose: (() => any) | undefined;

	const [field, subInjector] = $derived.by(() => {
		injectorDispose?.();
		const subInjector = createInjector({ providers: [], parent: rootInjector });
		injectorDispose = () => {
			subInjector.destroy();
			injectorDispose = undefined;
		};
		const field = convert(inputs.schema as any, {
			...inputs.options,
			handle: SvelteSchemaHandle as any,
			builder: SvelteFormBuilder,
			injector: subInjector
		});
		return [field, subInjector];
	});
	$effect.pre(() => {
		return () => {
			return injectorDispose?.();
		};
	});
	$effect.pre(() => {
		let ref: EffectRef | undefined;
		if (field.form.control) {
			ref = initListen(inputs.model, field!.form.control!, subInjector as Injector, (value) => {
				untracked(() => {
					if (field!.form.control?.valueNoError$$()) {
						inputs.modelChange?.(value);
					}
				});
			});
			field!.form.control?.updateValue(inputs.model);
		}

		return () => {
			ref?.destroy();
		};
	});
</script>

<FieldTemplate {field}></FieldTemplate>
