// packages/react/src/use-model/use-radio-model.ts
import { useMemo } from 'react';
import type { ControlValueAccessorAdapter } from '../util/use-control-value-accessor';

export function useInputRadioModel(
  cvaa: ControlValueAccessorAdapter,
  value: any,
) {
  return useMemo(() => {
    return {
      value,
      checked: Object.is(cvaa.value, value),
      disabled: cvaa.disabled,
      onBlur: cvaa.touchedChange,
      onChange: () => cvaa.valueChange(value),
    };
  }, [cvaa]);
}

// packages/solid/src/use-model/use-radio-model.ts
import { createMemo } from 'solid-js';
import type { ControlValueAccessorAdapter } from '../util/use-control-value-accessor';

export function useInputRadioModel(
  cvaa: ControlValueAccessorAdapter,
  value: any,
) {
  return createMemo(() => {
    return {
      value,
      checked: Object.is(cvaa.value(), value),
      disabled: cvaa.disabled(),
      onBlur: cvaa.touchedChange,
      onChange: () => cvaa.valueChange(value),
    };
  });
}
