// packages/svelte/src/lib/component/field-control-bind.svelte
<script lang="ts">
	import type { KeyPath } from '@piying/view-core';
	import { createViewControlLink, isFieldControl } from '@piying/view-core';
	import type { PiResolvedViewFieldConfig } from '../type/group';
	import { useControlValueAccessor } from '../util/use-control-value-accessor.svelte';

	let props: {
		field: PiResolvedViewFieldConfig;
		path?: KeyPath;
		children: (cvaa: any, field: PiResolvedViewFieldConfig) => any;
	} = $props();

	let dispose: ((destroy?: boolean) => void) | undefined;

	const resolvedField = $derived(props.path ? props.field.get(props.path)! : props.field);

	const { cva, cvaa } = useControlValueAccessor();
	$effect.pre(() => {
		dispose?.();
		const control = resolvedField?.form.control;
		if (!control) {
			throw new Error(
				`📍 fieldControlBind:[${props.field?.keyPath || ''}]->[${props.path || ''}]❗`
			);
		}
		if (!isFieldControl(control)) {
			throw new Error(`🏷️ fieldControl❗`);
		}
		dispose = createViewControlLink(() => control, cva, props.field.injector);
		return () => {
			dispose?.(true);
			dispose = undefined;
		};
	});
</script>

{@render props.children(cvaa, resolvedField)}

// packages/vue/src/component/field-control-bind.vue
<script setup lang="ts">
import { computed, onUnmounted, watch } from 'vue';
import type { KeyPath } from '@piying/view-core';
import { createViewControlLink, isFieldControl } from '@piying/view-core';
import type { PiResolvedViewFieldConfig } from '../type/group';
import { useControlValueAccessor } from '../util/use-control-value-accessor';

const props = defineProps<{
  field: PiResolvedViewFieldConfig;
  path?: KeyPath;
}>();

const resolvedField = computed(() => {
  const keyPath = props.path;
  return keyPath ? props.field.get(keyPath) : props.field;
});

let dispose: ((destroy?: boolean) => void) | undefined;
const { cva, cvaa } = useControlValueAccessor();

watch(
  [resolvedField],
  ([field]) => {
    dispose?.();
    if (field?.form?.control) {
      const control = field.form.control;
      if (!control) {
        throw new Error(`📍 fieldControlBind:[${field.keyPath || ''}]->[${props.path || ''}]❗`);
      }
      if (!isFieldControl(control)) {
        throw new Error(`🏷️ fieldControl❗`);
      }
      dispose = createViewControlLink(() => control, cva, field.injector);
    }
  },
  { immediate: true },
);

onUnmounted(() => {
  dispose?.(true);
  dispose = undefined;
});
</script>

<template>
  <slot :cvaa="cvaa" :field="resolvedField"> </slot>
</template>

<style scoped></style>
