// packages/svelte/src/lib/component/field-template.svelte
<script lang="ts">
	import type { PiResolvedViewFieldConfig } from '../type/group';
	import { signalToRef } from '../util/signal-convert.svelte';
	import { PI_VIEW_FIELD_TOKEN, InjectorToken, CVA } from '../token';
	import { createViewControlLink, isFieldControl } from '@piying/view-core';
	import { getContext, setContext } from 'svelte';
	import type { Injector } from 'static-injector';
	import PiWrapper from './wrapper.svelte';
	const props: {
		field: PiResolvedViewFieldConfig;
	} = $props();
	const injector = getContext<Injector>(InjectorToken)!;
	const attributes = signalToRef(() => props.field.attributes());
	const inputs = signalToRef(() => props.field.inputs());
	const outputs = signalToRef(() => props.field.outputs());
	const fieldInputs = $derived.by(() => ({ ...attributes, ...inputs, ...outputs }));

	let controlRef = $state<any>();
	const renderConfig = signalToRef(() => props.field.renderConfig());
	const control = $derived.by(() => props.field.form.control);
	$effect(() => {
		let dispose: (() => any) | undefined;
		if (controlRef?.cva) {
			dispose = createViewControlLink((() => control) as any, controlRef?.cva, injector);
		}
		return () => {
			dispose?.();
			dispose = undefined;
		};
	});
	const fieldChildren = signalToRef(() => props.field.children?.());

	const wrappers = signalToRef(() => props.field.wrappers());
	// todo lazy检查
	const ComponentType = $derived.by(() => props.field.define?.type);
	const field = $derived(props.field);
	setContext(PI_VIEW_FIELD_TOKEN, () => field);
</script>

{#if !renderConfig?.hidden}
	{#if field.define?.type}
		{#snippet children()}
			{#if fieldChildren}
				<ComponentType {...fieldInputs}></ComponentType>
			{:else if field.form.control}
				<ComponentType {...fieldInputs} bind:this={controlRef}></ComponentType>
			{:else}
				<ComponentType {...fieldInputs}></ComponentType>
			{/if}
		{/snippet}
		<PiWrapper wrappers={wrappers!} {children}></PiWrapper>
	{/if}
{/if}

// packages/vue/src/field-template.vue
<script setup lang="ts">
import {
  computed,
  defineAsyncComponent,
  onUnmounted,
  provide,
  ref,
  inject as vInject,
  watch,
} from 'vue';
import type { PiResolvedViewFieldConfig } from './type/group';
import { signalToRef } from './util/signal-convert';
import { PI_VIEW_FIELD_TOKEN, InjectorToken } from './token';
import PiWrapper from './wrapper.vue';
import { createViewControlLink, isFieldControl } from '@piying/view-core';
const props = defineProps<{
  field: PiResolvedViewFieldConfig;
}>();
const injector = vInject(InjectorToken)!;

const inputs = signalToRef(() => props.field.inputs());
const outputs = signalToRef(() => props.field.outputs());
const renderConfig = signalToRef(() => props.field.renderConfig());

const attributes = signalToRef(() => props.field.attributes());
const fieldInput = computed(() => ({ ...attributes.value, ...inputs.value }));
const fieldChildren = signalToRef(() => props.field.children?.());

const wrappers = signalToRef(() => props.field.wrappers());

const componentType = computed(() =>
  typeof props.field.define?.type === 'function'
    ? defineAsyncComponent(props.field.define?.type)
    : props.field.define?.type,
);
const field = computed(() => props.field);
provide(PI_VIEW_FIELD_TOKEN, field);
// 使用cva
const childRef = ref<any>(null);
const isControl = isFieldControl(field.value.form.control);
let dispose: (() => void) | undefined;

watch(
  [childRef, field],
  ([childRef, field]) => {
    dispose?.();
    if (isControl && childRef) {
      dispose = createViewControlLink((() => field.form.control) as any, childRef['cva'], injector);
    }
  },
  { immediate: true },
);
onUnmounted(() => {
  dispose?.();
  dispose = undefined;
});
</script>

<template>
  <template v-if="!renderConfig!.hidden">
    <template v-if="field.define?.type">
      <pi-wrapper v-bind:wrappers="wrappers!">
        <!-- group -->
        <template v-if="fieldChildren">
          <component :is="componentType" v-bind="fieldInput" v-on="outputs"></component>
        </template>
        <!-- control -->
        <template v-else>
          <template v-if="field.form.control">
            <component
              :is="componentType"
              v-bind="fieldInput"
              v-on="outputs"
              ref="childRef"
            ></component>
          </template>
          <template v-else>
            <component :is="componentType" v-bind="fieldInput" v-on="outputs"></component>
          </template>
        </template>
      </pi-wrapper>
    </template>
  </template>
</template>

<style scoped></style>
