// packages/vue/src/component/wrapper.vue
<script setup lang="ts">
import { computed } from 'vue';
import SelfComponent from './wrapper.vue';
import type { CoreResolvedWrapperConfig } from '@piying/view-core';
import { signalToRef } from '../util/signal-convert';

const dInputs = defineProps<{
  wrappers: CoreResolvedWrapperConfig[];
}>();
const restWrappers = computed(() => dInputs.wrappers!.slice(1));
const wrapper = computed(() => dInputs.wrappers[0]);
const inputs = signalToRef(() => ({ ...wrapper.value?.inputs(), ...wrapper.value?.attributes() }));
const outputs = computed(() => wrapper.value?.outputs?.() ?? {});
</script>

<template>
  <template v-if="wrapper">
    <component :is="wrapper.type" v-bind="inputs" v-on="outputs">
      <self-component v-bind="{ wrappers: restWrappers }">
        <slot></slot>
      </self-component>
    </component>
  </template>
  <template v-else>
    <slot></slot>
  </template>
</template>

<style scoped></style>

// packages/react/src/component/wrapper.tsx
import type { CoreResolvedWrapperConfig } from '@piying/view-core';
import { useMemo } from 'react';
import { useSignalToRef } from '../util/signal-convert';

export interface PiyingWrapperProps {
  wrappers: CoreResolvedWrapperConfig[];
  children: any;
}

export function PiyingWrapper(props: PiyingWrapperProps) {
  const restWrappers = useMemo(
    () => props.wrappers!.slice(1),
    [props.wrappers],
  );
  const wrapper = props.wrappers[0];
  const inputs = useSignalToRef(wrapper, () => ({
    ...wrapper?.inputs(),
    ...wrapper?.attributes(),
    ...wrapper?.outputs,
  }));
  return (
    <>
      {wrapper ? (
        <wrapper.type {...inputs}>
          <PiyingWrapper wrappers={restWrappers}>
            {props.children}
          </PiyingWrapper>
        </wrapper.type>
      ) : (
        props.children
      )}
    </>
  );
}
